name = "weather-agent"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[ai]
binding = "AI"

[[durable_objects.bindings]]
name = "CONVERSATIONS"
class_name = "ConversationDurableObject"

[[durable_objects.bindings]]
name = "CACHE"
class_name = "DurableObjectRateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["ConversationDurableObject"]

[[migrations]]
tag = "v2"
new_classes = ["DurableObjectRateLimiter"]

[observability]
enabled = true
